export const LOAD_PIZZA_SUCCESS = 'LOAD_PIZZA_SUCCESS';
export const CHECKOUT_PIZZA = 'CHECKOUT_PIZZA';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'